/**
 * Static copy for the driver ride screen (T-405). Every number (fare, earnings, distance) comes
 * from the server's RideResource; only labels live here.
 */
export const DRIVER_RIDE_COPY = {
  screenA11y: 'Current ride',
  back: 'Back',
  // Step titles.
  toPickup: 'Head to pickup',
  atPickup: 'Waiting for the passenger',
  onTrip: 'On trip',
  summary: 'Trip complete',
  cancelled: 'Ride cancelled',
  cancelledBody: 'This ride is no longer assigned to you.',
  unknown: 'Checking the ride…',
  noRide: 'You have no active ride.',
  backToMap: 'Back to map',
  openRide: 'Open ride',
  openRideA11y: 'Open your current ride',
  rideInProgress: 'Ride in progress',
  // Labels.
  passengerFallback: 'Passenger',
  noRating: 'New rider',
  pickup: 'Pickup',
  dropoff: 'Drop-off',
  stop: 'Stop',
  nextStop: 'Next stop',
  call: 'Call',
  callA11y: 'Call the passenger',
  navigate: 'Navigate',
  navigateA11y: 'Open directions in the maps app',
  // Actions.
  arrived: "I've arrived",
  start: 'Start trip',
  complete: 'Complete trip',
  completeStop: 'Stop done',
  cancel: 'Cancel ride',
  working: 'Please wait…',
  done: 'Done',
  // Summary.
  totalFare: 'Total fare',
  collectCash: 'Collect in cash',
  collectOther: 'Paid by',
  yourEarnings: 'Your earnings',
  base: 'Base fare',
  distance: 'Distance',
  time: 'Time',
  stopsFare: 'Stops',
  minFareAdjustment: 'Minimum fare adjustment',
  km: 'km',
  minutes: 'min',
  currency: 'PKR',
  // Cancel sheet.
  cancelTitle: 'Why are you cancelling?',
  cancelHint: 'The passenger will see this reason.',
  cancelPlaceholder: 'For example: the passenger is not at the pickup',
  cancelTooShort: 'Please write at least 3 characters.',
  cancelSubmit: 'Cancel ride',
  cancelKeep: 'Keep ride',
  // Toasts.
  arrivedDone: 'The passenger knows you have arrived.',
  startedDone: 'Trip started.',
  completedDone: 'Trip complete.',
  stopDone: 'Stop marked as done.',
  cancelledDone: 'Ride cancelled.',
  actionFailed: 'Could not update the ride. Please try again.',
  refreshFailed: 'Could not refresh the ride.',
  changedElsewhere: 'The ride changed. Showing the latest status.',
  notAssigned: 'This ride is no longer assigned to you.',
  cannotCancel: 'The ride can only be cancelled before the trip starts.',
  notNearPickup: 'You are not at the pickup yet.',
  /** Appended to the not-near-pickup message; `{m}` is the server's distance in metres. */
  aboutAway: 'About {m} m away.',
  callFailed: 'Could not start a call on this device.',
  navigateFailed: 'Could not open the maps app.',
} as const;
